
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>GEOBOX.OSC.IM.DataCheckerTool</RootNamespace>
    <AssemblyName>GEOBOX-DataCheckerTool</AssemblyName>
    <ApplicationIcon>geobox.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
	<GenerateBindingRedirectsOutputType>false</GenerateBindingRedirectsOutputType>
	<GenerateBindingRedirects>false</GenerateBindingRedirects>
	<AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<Deterministic>false</Deterministic>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>..\_output\</OutputPath>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>..\_output\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Includes\*.png" />
    <Resource Include="Includes\geobox.ico" />
    <Resource Include="geobox.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
